name: Python package  # Workflow name
on: [push, pull_request]  # Triggers
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -e .[dev]
    - name: Lint with flake8
      run: flake8 src tests
    - name: Run tests
      run: pytest -v --cov=config_manager